version: '3.8'
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: casino
      POSTGRES_PASSWORD: casino
      POSTGRES_DB: casino
    volumes:
      - db_data:/var/lib/postgresql/data
  web:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://casino:casino@db:5432/casino
      SESSION_SECRET: change-me
    ports:
      - "5000:5000"
volumes:
  db_data:
